version: '3'
services:
  ctfd:
    build: .
    container_name: ctfd
    ports:
      - "8000:8000"
  crypto_lightweight_prng:
    build: ./crypto/lightweight_prng
    container_name: crypto_lightweight_prng
    ports:
      - "50000:1337"
    restart: always
  web_simple_app_1:
    build: ./web/simple_app_1
    container_name: web_simple_app_1
    ports:
      - "50001:5000"
    restart: always
  pwn_hash_calculator:
    build: ./pwn/hash_calculator
    container_name: pwn_hash_calculator
    ports:
      - "50002:1337"
    restart: always
  web_janken_master:
    build: ./web/janken_master
    container_name: web_janken_master
    ports:
      - "50003:5000"
    restart: always
  pwn_login_shell:
    build: ./pwn/login_shell
    container_name: pwn_login_shell
    ports:
      - "50004:1337"
    restart: always
