version: '3'
services:
  ctfd:
    build: .
    container_name: ctfd
    ports:
      - "8000:8000"
  crypto_easy_prng:
    build: ./crypto/easy_prng
    container_name: crypto_easy_prng
    ports:
      - "50000:1337"
    restart: always
  web_simple_app_1:
    build: ./web/simple_app_1
    container_name: web_simple_app_1
    ports:
      - "50001:5000"
    restart: always
  pwn_hash_calculator:
    build: ./pwn/hash_calculator
    container_name: pwn_hash_calculator
    ports:
      - "50002:1337"
    restart: always
